// AUTO-GENERATED — DO NOT EDIT. Run npm run gen:policies

export interface Policy {
  schemaname: string;
  tablename: string;
  policyname: string;
  permissive: boolean;
  roles: string[];
  cmd: string;
  qual: string | null;
  with_check: string | null;
}

export const POLICIES: Policy[] = [
  {
    schemaname: 'public',
    tablename: 'organization_notification_settings',
    policyname: 'org_notification_settings_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organizations'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_payable',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'accounts_payable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_receivable',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'accounts_receivable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'activity_logs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'activity_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'asphalt_types',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'asphalt_types'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_log',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'audit_log'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_logs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'audit_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'avatars',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'avatars'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_packages',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'bid_packages'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_vendors',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'bid_vendors'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bids',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'bids'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bim_models',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'bim_models'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'certifications',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'certifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'change_orders',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'change_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'commitments',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'commitments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_checks',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'compliance_checks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_tracking',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'compliance_tracking'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'cost_codes',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'cost_codes'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_assignments',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'crew_assignments'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_members',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'crew_members'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crews',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'crews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'daily_logs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'daily_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dashboard_configs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'dashboard_configs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'document_references',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'document_references'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'documents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'drawing_versions',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'drawing_versions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dump_trucks',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'dump_trucks'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'employees',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'employees'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'equipment'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_assignments',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'equipment_assignments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_maintenance',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'equipment_maintenance'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_usage',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'equipment_usage'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimate_line_items',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'estimate_line_items'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimates',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'estimates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'financial_documents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'financial_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'general_ledger',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'general_ledger'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'hr_documents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'hr_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inspections',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'inspections'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'integration_tokens',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'integration_tokens'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inventory_transactions',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'inventory_transactions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'issues',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'issues'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'job_titles',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'job_titles'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'labor_records',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'labor_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_entries',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'line_item_entries'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_templates',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'line_item_templates'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_items',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'line_items'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'maps',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'maps'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_inventory',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'material_inventory'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_orders',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'material_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_receipts',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'material_receipts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'materials',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'materials'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'meeting_minutes',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'meeting_minutes'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'notifications',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "(user_id = auth.uid())",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_invites',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'organization_invites'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_members',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'organization_members'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_projects',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'organization_projects'::text, project_id, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organizations',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'organizations'::text, NULL::uuid, id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payments',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'payments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payroll',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'payroll'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'photos',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'photos'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'prequalifications',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'prequalifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'procurement_workflows',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'procurement_workflows'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'progress_billings',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'progress_billings'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'project_inspectors',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'project_inspectors'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'projects',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'projects'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'punch_lists',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'punch_lists'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'purchase_orders',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'purchase_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'quality_reviews',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'quality_reviews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'regulatory_documents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'regulatory_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'reports',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'reports'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'rfis',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'rfis'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'safety_incidents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'safety_incidents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'sensor_data',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'sensor_data'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontractor_agreements',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'subcontractor_agreements'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontracts',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'subcontracts'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'submittals',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'submittals'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tack_rates',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'tack_rates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_dependencies',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'task_dependencies'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_status_logs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'task_status_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tasks',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'tasks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'training_records',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'training_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'user_projects',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'user_projects'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_bid_packages',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'vendor_bid_packages'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_contacts',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'vendor_contacts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_documents',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'vendor_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_qualifications',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'vendor_qualifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendors',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'vendors'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'wbs',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'wbs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'workflows',
    policyname: 'p_check_access_delete',
    permissive: true,
    roles: [],
    cmd: 'DELETE',
    qual: "public.check_access_bool('delete'::text, 'workflows'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_payable',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'accounts_payable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_receivable',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'accounts_receivable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'activity_logs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'activity_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'asphalt_types',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'asphalt_types'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_log',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'audit_log'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_logs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'audit_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'avatars',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'avatars'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_packages',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'bid_packages'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_vendors',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'bid_vendors'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bids',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'bids'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bim_models',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'bim_models'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'certifications',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'certifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'change_orders',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'change_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'commitments',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'commitments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_checks',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'compliance_checks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_tracking',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'compliance_tracking'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'cost_codes',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'cost_codes'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_assignments',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'crew_assignments'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_members',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'crew_members'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crews',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'crews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'daily_logs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'daily_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dashboard_configs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'dashboard_configs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'document_references',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'document_references'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'documents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'drawing_versions',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'drawing_versions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dump_trucks',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'dump_trucks'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'employees',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'employees'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'equipment'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_assignments',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'equipment_assignments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_maintenance',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'equipment_maintenance'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_usage',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'equipment_usage'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimate_line_items',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'estimate_line_items'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimates',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'estimates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'financial_documents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'financial_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'general_ledger',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'general_ledger'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'hr_documents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'hr_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inspections',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'inspections'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'integration_tokens',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'integration_tokens'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inventory_transactions',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'inventory_transactions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'issues',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'issues'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'job_titles',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'job_titles'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'labor_records',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'labor_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_entries',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'line_item_entries'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_templates',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'line_item_templates'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_items',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'line_items'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'maps',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'maps'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_inventory',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'material_inventory'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_orders',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'material_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_receipts',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'material_receipts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'materials',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'materials'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'meeting_minutes',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'meeting_minutes'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'notifications',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "((user_id = auth.uid()) OR ((COALESCE((payload ->> 'scope'::text), 'personal'::text) = 'org_wide'::text) AND public.check_access_bool('select'::text, 'notifications'::text, NULL::uuid, public.try_parse_uuid((payload ->> 'organization_id'::text)))))",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_invites',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organization_invites'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_members',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organization_members'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_projects',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organization_projects'::text, project_id, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organizations',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organizations'::text, NULL::uuid, id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payments',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'payments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payroll',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'payroll'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'photos',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'photos'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'prequalifications',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'prequalifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'procurement_workflows',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'procurement_workflows'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'progress_billings',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'progress_billings'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'project_inspectors',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'project_inspectors'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'projects',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'projects'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'punch_lists',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'punch_lists'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'purchase_orders',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'purchase_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'quality_reviews',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'quality_reviews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'regulatory_documents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'regulatory_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'reports',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'reports'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'rfis',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'rfis'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'safety_incidents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'safety_incidents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'sensor_data',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'sensor_data'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontractor_agreements',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'subcontractor_agreements'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontracts',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'subcontracts'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'submittals',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'submittals'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tack_rates',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'tack_rates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_dependencies',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'task_dependencies'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_status_logs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'task_status_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tasks',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'tasks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'training_records',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'training_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'user_projects',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'user_projects'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_bid_packages',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'vendor_bid_packages'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_contacts',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'vendor_contacts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_documents',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'vendor_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_qualifications',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'vendor_qualifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendors',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'vendors'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'wbs',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'wbs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'workflows',
    policyname: 'p_check_access_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'workflows'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_payable',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'accounts_payable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'accounts_receivable',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'accounts_receivable'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'activity_logs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'activity_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'asphalt_types',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'asphalt_types'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_log',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'audit_log'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'audit_logs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'audit_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'avatars',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'avatars'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_packages',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'bid_packages'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bid_vendors',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'bid_vendors'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bids',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'bids'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'bim_models',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'bim_models'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'certifications',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'certifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'change_orders',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'change_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'commitments',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'commitments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_checks',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'compliance_checks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'compliance_tracking',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'compliance_tracking'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'cost_codes',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'cost_codes'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_assignments',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'crew_assignments'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crew_members',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'crew_members'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'crews',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'crews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'daily_logs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'daily_logs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dashboard_configs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'dashboard_configs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'document_references',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'document_references'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'documents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'drawing_versions',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'drawing_versions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'dump_trucks',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'dump_trucks'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'employees',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'employees'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'equipment'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_assignments',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'equipment_assignments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_maintenance',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'equipment_maintenance'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'equipment_usage',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'equipment_usage'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimate_line_items',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'estimate_line_items'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'estimates',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'estimates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'financial_documents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'financial_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'general_ledger',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'general_ledger'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'hr_documents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'hr_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inspections',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'inspections'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'integration_tokens',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'integration_tokens'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'inventory_transactions',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'inventory_transactions'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'issues',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'issues'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'job_titles',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'job_titles'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'labor_records',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'labor_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_entries',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'line_item_entries'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_item_templates',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'line_item_templates'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'line_items',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'line_items'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'maps',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'maps'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_inventory',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'material_inventory'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_orders',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'material_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'material_receipts',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'material_receipts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'materials',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'materials'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'meeting_minutes',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'meeting_minutes'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'notifications',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "(user_id = auth.uid())) WITH CHECK ((user_id = auth.uid())",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_invites',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "(public.check_access_bool('update'::text, 'organization_invites'::text, NULL::uuid, organization_id) OR (invited_profile_id = auth.uid()))) WITH CHECK ((public.check_access_bool('update'::text, 'organization_invites'::text, NULL::uuid, organization_id) OR ((invited_profile_id = auth.uid()) AND (invited_by_profile_id = auth.uid()) AND (status = 'pending'::text)))",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_members',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'organization_members'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_projects',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'organization_projects'::text, project_id, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organizations',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'organizations'::text, NULL::uuid, id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payments',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'payments'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'payroll',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'payroll'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'photos',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'photos'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'prequalifications',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'prequalifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'procurement_workflows',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'procurement_workflows'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'progress_billings',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'progress_billings'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'project_inspectors',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'project_inspectors'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'projects',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'projects'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'punch_lists',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'punch_lists'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'purchase_orders',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'purchase_orders'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'quality_reviews',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'quality_reviews'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'regulatory_documents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'regulatory_documents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'reports',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'reports'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'rfis',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'rfis'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'safety_incidents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'safety_incidents'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'sensor_data',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'sensor_data'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontractor_agreements',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'subcontractor_agreements'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'subcontracts',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'subcontracts'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'submittals',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'submittals'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tack_rates',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'tack_rates'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_dependencies',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'task_dependencies'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'task_status_logs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'task_status_logs'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'tasks',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'tasks'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'training_records',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'training_records'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'user_projects',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'user_projects'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_bid_packages',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'vendor_bid_packages'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_contacts',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'vendor_contacts'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_documents',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'vendor_documents'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendor_qualifications',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'vendor_qualifications'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'vendors',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'vendors'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'wbs',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'wbs'::text, project_id, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'workflows',
    policyname: 'p_check_access_update',
    permissive: true,
    roles: [],
    cmd: 'UPDATE',
    qual: "public.check_access_bool('update'::text, 'workflows'::text, NULL::uuid, NULL::uuid)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'organization_notification_settings',
    policyname: 'p_org_notification_settings_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "public.check_access_bool('select'::text, 'organizations'::text, NULL::uuid, organization_id)",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'user_notification_settings',
    policyname: 'p_user_notification_settings_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "(user_id = auth.uid())",
    with_check: null,
  },
  {
    schemaname: 'public',
    tablename: 'user_notification_settings',
    policyname: 'user_notification_settings_select',
    permissive: true,
    roles: [],
    cmd: 'SELECT',
    qual: "(user_id = auth.uid())",
    with_check: null,
  },
];
