export const rpcDefinitions = {
  calculate_cy: { args: 'length numeric, width numeric, depth numeric', return: 'numeric' },
  calculate_sy: { args: 'length numeric, width numeric', return: 'numeric' },
  calculate_tons: { args: 'volume numeric, density numeric', return: 'numeric' },
  check_is_admin: { args: '', return: 'boolean' },
  custom_access_token_hook: { args: 'claims jsonb', return: 'jsonb' },
  delete_asphalt_type: { args: '_id uuid', return: 'void' },
  delete_avatars: { args: '_id uuid', return: 'void' },
  delete_change_order: { args: '_id uuid', return: 'void' },
  delete_contract: { args: '_id uuid', return: 'void' },
  delete_contract_organization: { args: '_id uuid', return: 'void' },
  delete_crew: { args: '_id uuid', return: 'void' },
  delete_crew_member: { args: '_id uuid', return: 'void' },
  delete_crews: { args: '_id uuid', return: 'void' },
  delete_daily_log: { args: '_id uuid', return: 'void' },
  delete_dump_truck: { args: '_id uuid', return: 'void' },
  delete_equipment: { args: '_id uuid', return: 'void' },
  delete_equipment_assignment: { args: '_id uuid', return: 'void' },
  delete_equipment_usage: { args: '_id uuid', return: 'void' },
  delete_inspection: { args: '_id uuid', return: 'void' },
  delete_issue: { args: '_id uuid', return: 'void' },
  delete_issues: { args: '_id uuid', return: 'void' },
  delete_job_title: { args: '_id uuid', return: 'void' },
  delete_line_item: { args: '_id uuid', return: 'void' },
  delete_line_item_entry: { args: '_id uuid', return: 'void' },
  delete_line_item_template: { args: '_id uuid', return: 'void' },
  delete_map: { args: '_id uuid', return: 'void' },
  delete_organization: { args: '_id uuid', return: 'void' },
  delete_profile: { args: '_id uuid', return: 'void' },
  delete_tack_rates: { args: '_id uuid', return: 'void' },
  delete_user_contract: { args: '_user_id uuid, _contract_id uuid', return: 'void' },
  delete_wbs: { args: '_id uuid', return: 'void' },
  filtered_by_axle_count_dump_trucks: { args: '_axle_count numeric', return: 'SETOF' },
  filtered_by_contract_daily_logs: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_dump_trucks: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_equipment_assignments: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_equipment_usage: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_inspections: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_issues: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_line_item_entries: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_contract_user_contracts: { args: '_contract_id uuid', return: 'SETOF' },
  filtered_by_crew_crew_members: { args: '_crew_id uuid', return: 'SETOF' },
  filtered_by_entered_by_line_item_entries: { args: '_entered_by uuid', return: 'SETOF' },
  filtered_by_equipment_equipment_assignments: { args: '_equipment_id uuid', return: 'SETOF' },
  filtered_by_equipment_equipment_usage: { args: '_equipment_id uuid', return: 'SETOF' },
  filtered_by_equipment_issues: { args: '_equipment_id uuid', return: 'SETOF' },
  filtered_by_line_code_line_items: { args: '_line_code text', return: 'SETOF' },
  filtered_by_line_item_equipment_assignments: { args: '_line_item_id uuid', return: 'SETOF' },
  filtered_by_line_item_equipment_usage: { args: '_line_item_id uuid', return: 'SETOF' },
  filtered_by_line_item_inspections: { args: '_line_item_id uuid', return: 'SETOF' },
  filtered_by_line_item_issues: { args: '_line_item_id uuid', return: 'SETOF' },
  filtered_by_line_item_line_item_entries: { args: '_line_item_id uuid', return: 'SETOF' },
  filtered_by_map_equipment_assignments: { args: '_map_id uuid', return: 'SETOF' },
  filtered_by_map_equipment_usage: { args: '_map_id uuid', return: 'SETOF' },
  filtered_by_map_inspections: { args: '_map_id uuid', return: 'SETOF' },
  filtered_by_map_issues: { args: '_map_id uuid', return: 'SETOF' },
  filtered_by_map_line_item_entries: { args: '_map_id uuid', return: 'SETOF' },
  filtered_by_max_volume_dump_trucks: { args: '_max_volume numeric', return: 'SETOF' },
  filtered_by_operator_equipment_assignments: { args: '_operator_id uuid', return: 'SETOF' },
  filtered_by_operator_equipment_usage: { args: '_operator_id uuid', return: 'SETOF' },
  filtered_by_organization_contracts: { args: '_organization_id uuid', return: 'SETOF' },
  filtered_by_organization_crews: { args: '_organization_id uuid', return: 'SETOF' },
  filtered_by_organization_equipment: { args: '_organization_id uuid', return: 'SETOF' },
  filtered_by_organization_line_item_templates: { args: '_organization_id uuid', return: 'SETOF' },
  filtered_by_organization_profiles: { args: '_organization_id uuid', return: 'SETOF' },
  filtered_by_output_unit_line_item_templates: { args: '_output_unit public.unit_measure_type', return: 'SETOF' },
  filtered_by_payload_capacity_dump_trucks: { args: '_payload_capacity_tons numeric', return: 'SETOF' },
  filtered_by_priority_issues: { args: '_priority public.priority', return: 'SETOF' },
  filtered_by_role_profiles: { args: '_role public.user_role', return: 'SETOF' },
  filtered_by_role_user_contracts: { args: '_role public.user_role', return: 'SETOF' },
  filtered_by_unit_measure_line_items: { args: '_unit_measure public.unit_measure_type', return: 'SETOF' },
  filtered_by_user_user_contracts: { args: '_user_id uuid', return: 'SETOF' },
  filtered_by_wbs_equipment_assignments: { args: '_wbs_id uuid', return: 'SETOF' },
  filtered_by_wbs_equipment_usage: { args: '_wbs_id uuid', return: 'SETOF' },
  filtered_by_wbs_inspections: { args: '_wbs_id uuid', return: 'SETOF' },
  filtered_by_wbs_issues: { args: '_wbs_id uuid', return: 'SETOF' },
  filtered_by_wbs_line_item_entries: { args: '_wbs_id uuid', return: 'SETOF' },
  get_asphalt_types: { args: '', return: 'SETOF' },
  get_change_orders_count_for_contract: { args: 'contract_id_param uuid', return: 'integer' },
  get_contract_organizations: { args: 'contract_id uuid', return: 'TABLE(organization_id' },
  get_dashboard_metrics: { args: '_user_id uuid', return: 'TABLE(active_contracts' },
  get_enriched_user_contracts: { args: '_user_id uuid', return: 'TABLE(id' },
  get_enum_values: { args: 'enum_type text', return: 'TABLE(value' },
  get_inspections_count_for_contract: { args: 'contract_id_param uuid', return: 'integer' },
  get_issues_count_for_contract: { args: 'contract_id_param uuid', return: 'integer' },
  handle_updated_at: { args: '', return: 'trigger' },
  insert_asphalt_type: { args: '_name text, _compaction_min numeric DEFAULT NULL::numeric, _jmf_temp_max numeric DEFAULT NULL::numeric, _jmf_temp_min numeric DEFAULT NULL::numeric, _lift_depth_inches numeric DEFAULT NULL::numeric, _notes text DEFAULT NULL::text, _target_spread_rate_lbs_per_sy numeric DEFAULT NULL::numeric', return: 'uuid' },
  insert_contract: { args: '_title text, _location text, _start_date date, _end_date date, _status public.contract_status DEFAULT 'Draft'::public.contract_status, _budget numeric DEFAULT NULL::numeric, _description text DEFAULT NULL::text, _coordinates jsonb DEFAULT NULL::jsonb, _created_by uuid DEFAULT NULL::uuid', return: 'uuid' },
  insert_dump_truck: { args: '_payload_capacity_tons numeric, _truck_identifier text, _axle_count numeric DEFAULT NULL::numeric, _bed_height numeric DEFAULT NULL::numeric, _bed_length numeric DEFAULT NULL::numeric, _bed_volume numeric DEFAULT NULL::numeric, _bed_width numeric DEFAULT NULL::numeric, _contract_id uuid DEFAULT NULL::uuid, _equipment_id uuid DEFAULT NULL::uuid, _hoist_bottom numeric DEFAULT NULL::numeric, _hoist_top numeric DEFAULT NULL::numeric, _hoist_width numeric DEFAULT NULL::numeric, _notes text DEFAULT NULL::text', return: 'uuid' },
  insert_line_item_entry: { args: '_contract_id uuid, _line_item_id uuid, _map_id uuid, _input_variables jsonb, _wbs_id uuid, _computed_output numeric DEFAULT NULL::numeric, _notes text DEFAULT NULL::text, _output_unit public.unit_measure_type DEFAULT NULL::public.unit_measure_type, _entered_by uuid DEFAULT NULL::uuid', return: 'uuid' },
  insert_profile_full: { args: '_role public.user_role, _full_name text, _email text, _username text, _id uuid DEFAULT gen_random_uuid(), _phone text DEFAULT NULL::text, _location text DEFAULT NULL::text, _job_title_id uuid DEFAULT NULL::uuid, _custom_job_title text DEFAULT NULL::text, _organization_id uuid DEFAULT NULL::uuid, _custom_organization_name text DEFAULT NULL::text, _avatar_id uuid DEFAULT NULL::uuid', return: 'uuid' },
  lock_budget_on_status_change: { args: '', return: 'trigger' },
  prevent_daily_log_if_inactive: { args: '', return: 'trigger' },
  update_asphalt_type: { args: '_id uuid, _name text DEFAULT NULL::text, _compaction_min numeric DEFAULT NULL::numeric, _jmf_temp_max numeric DEFAULT NULL::numeric, _jmf_temp_min numeric DEFAULT NULL::numeric, _lift_depth_inches numeric DEFAULT NULL::numeric, _notes text DEFAULT NULL::text, _target_spread_rate_lbs_per_sy numeric DEFAULT NULL::numeric', return: 'void' },
  update_change_order: { args: '_id uuid, _title text DEFAULT NULL::text, _description text DEFAULT NULL::text, _attachments text[] DEFAULT NULL::text[], _new_quantity numeric DEFAULT NULL::numeric, _new_unit_price numeric DEFAULT NULL::numeric, _status public.change_order_status DEFAULT NULL::public.change_order_status, _approved_by uuid DEFAULT NULL::uuid, _approved_date timestamp with time zone DEFAULT NULL::timestamp with time zone, _updated_by uuid DEFAULT NULL::uuid', return: 'void' },
  update_contract: { args: '_id uuid, _title text DEFAULT NULL::text, _location text DEFAULT NULL::text, _start_date date DEFAULT NULL::date, _end_date date DEFAULT NULL::date, _status public.contract_status DEFAULT NULL::public.contract_status, _budget numeric DEFAULT NULL::numeric, _description text DEFAULT NULL::text, _coordinates jsonb DEFAULT NULL::jsonb', return: 'void' },
  update_contract_budget: { args: '', return: 'trigger' },
  update_contract_organization: { args: '_id uuid, _role public.organization_role DEFAULT NULL::public.organization_role, _notes text DEFAULT NULL::text, _updated_at timestamp with time zone DEFAULT now()', return: 'void' },
  update_dump_truck: { args: '_id uuid, _payload_capacity_tons numeric DEFAULT NULL::numeric, _truck_identifier text DEFAULT NULL::text, _axle_count numeric DEFAULT NULL::numeric, _bed_height numeric DEFAULT NULL::numeric, _bed_length numeric DEFAULT NULL::numeric, _bed_volume numeric DEFAULT NULL::numeric, _bed_width numeric DEFAULT NULL::numeric, _contract_id uuid DEFAULT NULL::uuid, _equipment_id uuid DEFAULT NULL::uuid, _hoist_bottom numeric DEFAULT NULL::numeric, _hoist_top numeric DEFAULT NULL::numeric, _hoist_width numeric DEFAULT NULL::numeric, _notes text DEFAULT NULL::text', return: 'void' },
  update_line_item_entry: { args: '_id uuid, _computed_output numeric DEFAULT NULL::numeric, _contract_id uuid DEFAULT NULL::uuid, _line_item_id uuid DEFAULT NULL::uuid, _map_id uuid DEFAULT NULL::uuid, _input_variables jsonb DEFAULT NULL::jsonb, _notes text DEFAULT NULL::text, _output_unit public.unit_measure_type DEFAULT NULL::public.unit_measure_type, _entered_by uuid DEFAULT NULL::uuid, _wbs_id uuid DEFAULT NULL::uuid', return: 'void' },
  validate_formula_unit: { args: '', return: 'trigger' },
  validate_formula_units: { args: '', return: 'trigger' },
  insert_project: { args: '_external_id text, _contract_id uuid, _name text, _start_date date, _end_date date', return: 'uuid' },
  update_project: { args: '_id uuid, _name text, _start_date date, _end_date date', return: 'void' },
  delete_project: { args: '_id uuid', return: 'void' },
  insert_estimate: { args: '_external_id text, _contract_id uuid, _title text, _amount numeric, _status text', return: 'uuid' },
  delete_estimate: { args: '_id uuid', return: 'void' },
  insert_cost_code: { args: '_external_id text, _contract_id uuid, _code text, _description text', return: 'uuid' },
  insert_schedule_task: { args: '_external_id text, _contract_id uuid, _name text, _start_date date, _end_date date, _percent_complete numeric', return: 'uuid' },
} as const;

export type RpcName = keyof typeof rpcDefinitions;
