import { createClient } from "@supabase/supabase-js";
import type { Database } from "./database.types"; // ←  auto-generated by Supabase
import { getRequiredEnv } from "@/utils/env-validator";

/*  ▸ Environment variables
    Vite/Next/etc. should expose these two variables at build time.
    Replace with your own env accessors if different.                */
const supabaseUrl = getRequiredEnv("VITE_SUPABASE_URL");
const supabaseAnon = getRequiredEnv("VITE_SUPABASE_ANON_KEY");

/*  ▸ The typed client
    We keep auth persistence on (default) so demo users stay logged in
    across reloads. Feel free to tweak the `Global` options object.    */
export const supabase = createClient<Database>(supabaseUrl, supabaseAnon, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
